In [ ]:
import pandas as pd
import altair as alt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Faltas_CC_U_Amonestaciones.csv to Faltas_CC_U_Amonestaciones (2).csv

In [ ]:
df = pd.read_csv("Faltas_CC_U_Amonestaciones.csv")

In [ ]:
import pandas as pd
# Configurar pandas para mostrar todas las columnas
pd.set_option('display.max_columns', None)
display(df.head())

,fecha,Copa,estadio,espectadores,arbitr,equipo 1,equipo 2,resultado,jugador_1,jugador_2,jugador_3,jugador_4,jugador_5,jugador_6,jugador_7,jugador_8,jugador_9,jugador_10,jugador_11,jugador_12,jugador_13,tipo-falta-1,tipo-falta-2,tipo-falta-3,tipo-falta-4,tipo-falta-5,tipo-falta-6,tipo-falta-7,tipo-falta-8,tipo-falta-9,tipo-falta-10,tipo-falta-11,tipo-falta-12,tipo-falta-13,tipo-falta-14,tipo-falta-15,tipo-falta-16,tipo-falta-17,tipo-falta-18,tipo-falta-19,tipo-falta-20,tipo-falta-21,equipo-jugador_1,equipo-jugador_2,equipo-jugador_3,equipo-jugador_4,equipo-jugador_5,equipo-jugador_6,equipo-jugador_7,equipo-jugador_8,equipo-jugador_9,equipo-jugador_10,equipo-jugador_11,equipo-jugador_12,equipo-jugador_13
0,Semifinales ...,Copa Apertura,Nacional Julio Martínez Prádanos,25.000 Espectadores,Mario Sánchez,Universidad de Chile,CSD Colo-Colo,3:1(1:1),Eduardo Arancibia,Mauricio Aros,Emerson Pereira,Clarence Acuña,Jaime Lopresti,Cristian Flores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eduardo Arancibia\n\n ...,Eduardo Arancibia,Mauricio Aros\n\n ...,Mauricio Aros,Emerson Pereira\n\n ...,Clarence Acuña\n\n ...,Clarence Acuña,Jaime Lopresti\n\n ...,Cristian Flores\n\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Universidad de Chile,Universidad de Chile,CSD Colo-Colo,Universidad de Chile,CSD Colo-Colo,CSD Colo-Colo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9. Jornada ...,Primera División de Chile,Nacional Julio Martínez Prádanos,40.000 Espectadores,Eduardo Gamboa Martínez,Universidad de Chile,CSD Colo-Colo,3:1(1:0),Diego Rivarola,Marco Villaseca,Marcelo Ramírez,Emerson Pereira,Jaime Lopresti,Cristian Flores,Leonardo Rodríguez,Francisco Rojas,NaN,NaN,NaN,NaN,NaN,Diego Rivarola\n\n ...,Diego Rivarola,Marco Villaseca\n\n ...,Marcelo Ramírez\n\n ...,Emerson Pereira\n\n ...,Jaime Lopresti\n\n ...,Cristian Flores\n\n ...,Leonardo Rodríguez\n\n ...,Leonardo Rodríguez,Francisco Rojas\n\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Universidad de Chile,CSD Colo-Colo,CSD Colo-Colo,CSD Colo-Colo,CSD Colo-Colo,CSD Colo-Colo,Universidad de Chile,CSD Colo-Colo,NaN,NaN,NaN,NaN,NaN
2,24. Jornada ...,Primera División de Chile,Monumental David Arellano,33.537 Espectadores,Robert Troxler,CSD Colo-Colo,Universidad de Chile,1:3(0:0),Diego Rivarola,Raúl Muñoz,Rafael Olarra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diego Rivarola\n\n ...,Raúl Muñoz\n\n ...,Raúl Muñoz,Rafael Olarra\n\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Universidad de Chile,CSD Colo-Colo,Universidad de Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4. Jornada ...,Primera División de Chile,Nacional Julio Martínez Prádanos,NaN,Guido Aros,Universidad de Chile,CSD Colo-Colo,1:1(0:0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19. Jornada ...,Primera División de Chile,Monumental David Arellano,NaN,Eduardo Ponce,CSD Colo-Colo,Universidad de Chile,2:3(1:1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Calcular el total de valores nulos por columna
null_counts = df.isnull().sum()

# Filtrar para mostrar solo las columnas que tienen al menos un valor nulo
null_summary = null_counts[null_counts > 0].sort_values(ascending=False)

print("Resumen de columnas con valores nulos:")
display(null_summary)

Resumen de columnas con valores nulos:

tipo-falta-21        62
tipo-falta-20        61
jugador_13           60
equipo-jugador_13    60
tipo-falta-19        60
tipo-falta-18        57
tipo-falta-17        57
jugador_12           56
equipo-jugador_12    56
tipo-falta-16        55
jugador_11           52
equipo-jugador_11    52
equipo-jugador_10    50
jugador_10           50
tipo-falta-15        49
tipo-falta-14        48
equipo-jugador_9     44
jugador_9            44
tipo-falta-13        42
tipo-falta-12        36
jugador_8            35
equipo-jugador_8     35
tipo-falta-11        32
equipo-jugador_7     26
tipo-falta-10        26
jugador_7            26
tipo-falta-9         20
jugador_6            17
equipo-jugador_6     17
tipo-falta-8         16
equipo-jugador_5     10
jugador_5            10
tipo-falta-7          9
espectadores          8
equipo-jugador_4      7
tipo-falta-6          7
tipo-falta-5          7
jugador_4             7
jugador_3             4
tipo-falta-4          4
equipo-jugador_3      4
tipo-falta-3          3
jugador_2             3
tipo-falta-2          3
equipo-jugador_2      3
jugador_1             2
tipo-falta-1          2
equipo-jugador_1      2
dtype: int64

In [ ]:
df.head()

,fecha,Copa,estadio,espectadores,arbitr,equipo 1,equipo 2,resultado,jugador_1,jugador_2,jugador_3,jugador_4,jugador_5,jugador_6,jugador_7,jugador_8,jugador_9,jugador_10,jugador_11,jugador_12,jugador_13,tipo-falta-1,tipo-falta-2,tipo-falta-3,tipo-falta-4,tipo-falta-5,tipo-falta-6,tipo-falta-7,tipo-falta-8,tipo-falta-9,tipo-falta-10,tipo-falta-11,tipo-falta-12,tipo-falta-13,tipo-falta-14,tipo-falta-15,tipo-falta-16,tipo-falta-17,tipo-falta-18,tipo-falta-19,tipo-falta-20,tipo-falta-21,equipo-jugador_1,equipo-jugador_2,equipo-jugador_3,equipo-jugador_4,equipo-jugador_5,equipo-jugador_6,equipo-jugador_7,equipo-jugador_8,equipo-jugador_9,equipo-jugador_10,equipo-jugador_11,equipo-jugador_12,equipo-jugador_13
0,Semifinales ...,Copa Apertura,Nacional Julio Martínez Prádanos,25.000 Espectadores,Mario Sánchez,Universidad de Chile,CSD Colo-Colo,3:1(1:1),Eduardo Arancibia,Mauricio Aros,Emerson Pereira,Clarence Acuña,Jaime Lopresti,Cristian Flores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eduardo Arancibia\n\n ...,Eduardo Arancibia,Mauricio Aros\n\n ...,Mauricio Aros,Emerson Pereira\n\n ...,Clarence Acuña\n\n ...,Clarence Acuña,Jaime Lopresti\n\n ...,Cristian Flores\n\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Universidad de Chile,Universidad de Chile,CSD Colo-Colo,Universidad de Chile,CSD Colo-Colo,CSD Colo-Colo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9. Jornada ...,Primera División de Chile,Nacional Julio Martínez Prádanos,40.000 Espectadores,Eduardo Gamboa Martínez,Universidad de Chile,CSD Colo-Colo,3:1(1:0),Diego Rivarola,Marco Villaseca,Marcelo Ramírez,Emerson Pereira,Jaime Lopresti,Cristian Flores,Leonardo Rodríguez,Francisco Rojas,NaN,NaN,NaN,NaN,NaN,Diego Rivarola\n\n ...,Diego Rivarola,Marco Villaseca\n\n ...,Marcelo Ramírez\n\n ...,Emerson Pereira\n\n ...,Jaime Lopresti\n\n ...,Cristian Flores\n\n ...,Leonardo Rodríguez\n\n ...,Leonardo Rodríguez,Francisco Rojas\n\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Universidad de Chile,CSD Colo-Colo,CSD Colo-Colo,CSD Colo-Colo,CSD Colo-Colo,CSD Colo-Colo,Universidad de Chile,CSD Colo-Colo,NaN,NaN,NaN,NaN,NaN
2,24. Jornada ...,Primera División de Chile,Monumental David Arellano,33.537 Espectadores,Robert Troxler,CSD Colo-Colo,Universidad de Chile,1:3(0:0),Diego Rivarola,Raúl Muñoz,Rafael Olarra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diego Rivarola\n\n ...,Raúl Muñoz\n\n ...,Raúl Muñoz,Rafael Olarra\n\n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Universidad de Chile,CSD Colo-Colo,Universidad de Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4. Jornada ...,Primera División de Chile,Nacional Julio Martínez Prádanos,NaN,Guido Aros,Universidad de Chile,CSD Colo-Colo,1:1(0:0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19. Jornada ...,Primera División de Chile,Monumental David Arellano,NaN,Eduardo Ponce,CSD Colo-Colo,Universidad de Chile,2:3(1:1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
import pandas as pd
import re

# 1. Extraer la fecha y el año
def extraer_fecha(texto):
    if pd.isna(texto):
        return None
    match = re.search(r'\|.*(\d{2}/\d{2}/\d{2})', str(texto))
    return match.group(1) if match else None

df['fecha_dt'] = pd.to_datetime(df['fecha'].apply(extraer_fecha), format='%d/%m/%y', errors='coerce')
df['Año'] = df['fecha_dt'].dt.year

# 2. Identificar columnas de tipo-falta
columnas_falta = [col for col in df.columns if 'tipo-falta' in col]

# 3. Contar cuántas faltas hay en cada fila (sumando entradas no nulas en esas columnas)
df['total_faltas_fila'] = df[columnas_falta].notna().sum(axis=1)

# 4. Agrupar por año sumando las faltas reales
faltas_por_año = df.groupby('Año')['total_faltas_fila'].sum().reset_index()
faltas_por_año.columns = ['Año', 'Cantidad de Faltas']

print("Resumen de amonestaciones reales por año (basado en entradas 'tipo-falta'):")
display(faltas_por_año)

Resumen de amonestaciones reales por año (basado en entradas 'tipo-falta'):

     Año  Cantidad de Faltas
0   2000                  23
1   2001                   0
2   2002                  11
3   2003                  15
4   2004                  25
5   2005                  36
6   2006                  41
7   2007                  36
8   2008                  21
9   2009                  24
10  2010                  31
11  2011                  33
12  2012                  64
13  2013                  21
14  2014                  28
15  2015                  21
16  2016                  23
17  2017                  26
18  2018                  33
19  2019                  20
20  2020                  21
21  2021                  25
22  2022                  17
23  2023                  13
24  2024                   8
25  2025                  45
26  2026                   6

In [ ]:
import pandas as pd

# Identificar todas las columnas que contienen 'tipo-falta'
columnas_falta = [col for col in df.columns if 'tipo-falta' in col]

# Crear una lista para almacenar todos los nombres de jugadores encontrados en esas columnas
todos_los_jugadores = []

for col in columnas_falta:
    # Extraemos el contenido, eliminamos nulos y limpiamos saltos de línea/espacios
    nombres = df[col].dropna().astype(str).str.split('\n').str[0].str.strip()
    todos_los_jugadores.extend(nombres.tolist())

# Convertir a Series para contar frecuencias
conteo_faltas = pd.Series(todos_los_jugadores).value_counts().reset_index()
conteo_faltas.columns = ['Jugador', 'Cantidad de Faltas']

# Mostrar los top 15 jugadores con más faltas
print("Top 15 jugadores con más amonestaciones acumuladas:")
display(conteo_faltas.head(15))

Top 15 jugadores con más amonestaciones acumuladas:

             Jugador  Cantidad de Faltas
0         José Rojas                  18
1          Luis Mena                  14
2   Matías Rodríguez                  14
3       Marcelo Díaz                  14
4     Gonzalo Fierro                  12
5     Diego Rivarola                  12
6      Claudio Baeza                  11
7      Manuel Iturra                  11
8    Jean Beausejour                  11
9    Esteban Paredes                  10
10  Osvaldo González                  10
11  Rodrigo Meléndez                  10
12  Charles Aránguiz                   9
13       Luis Musrri                   8
14     Gabriel Suazo                   8

In [ ]:
import altair as alt

# Graficar la tendencia de faltas por año usando barras
chart_year = alt.Chart(faltas_por_año).mark_bar(color='#4c78a8').encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Cantidad de Faltas:Q', title='Total de Amonestaciones'),
    tooltip=['Año', 'Cantidad de Faltas']
).properties(
    title='Evolución de Amonestaciones por Año (Gráfico de Barras)',
    width=600,
    height=300
).interactive()

display(chart_year)

alt.Chart(...)

In [62]:
import pandas as pd
import altair as alt

# Identificar columnas de tipo-falta
columnas_falta = [col for col in df.columns if 'tipo-falta' in col]

# Preparar una lista para expandir los datos
registros_detallados = []

for idx, row in df.iterrows():
    anio = row['Año']
    if pd.isna(anio): continue

    for col in columnas_falta:
        contenido = str(row[col]).lower()
        if pd.isna(row[col]) or contenido == 'nan' or contenido == '': continue

        # Lógica especial: si es segunda amarilla, cuenta como roja también
        es_amarilla = 'amarilla' in contenido
        es_roja = 'roja' in contenido
        es_segunda = 'segunda' in contenido or '2da' in contenido

        if es_amarilla:
            registros_detallados.append({'Año': int(anio), 'Tipo': 'Amarilla'})
            if es_segunda:
                registros_detallados.append({'Año': int(anio), 'Tipo': 'Roja'})
        elif es_roja:
            registros_detallados.append({'Año': int(anio), 'Tipo': 'Roja'})
        else:
            registros_detallados.append({'Año': int(anio), 'Tipo': 'Otros'})

# Crear DataFrame de detalles
df_detalle_faltas = pd.DataFrame(registros_detallados)

# Agrupar y contar
tendencia_tipos = df_detalle_faltas.groupby(['Año', 'Tipo']).size().reset_index(name='Cantidad')

# Calcular el Total por año
tendencia_total = tendencia_tipos.groupby('Año')['Cantidad'].sum().reset_index()
tendencia_total['Tipo'] = 'Total'

# Combinar
data_grafico = pd.concat([tendencia_tipos, tendencia_total])

# Filtrar categorías principales
data_grafico = data_grafico[data_grafico['Tipo'].isin(['Amarilla', 'Roja', 'Total'])]

# Graficar con colores más contrastados
chart_detallado = alt.Chart(data_grafico).mark_line(point=True).encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Cantidad:Q', title='Cantidad'),
    color=alt.Color('Tipo:N',
                    scale=alt.Scale(domain=['Total', 'Amarilla', 'Roja'],
                                   range=['#333333', '#D4AF37', '#CC0000']),
                    title='Tipo de Sanción'),
    tooltip=['Año', 'Tipo', 'Cantidad']
).properties(
    title='Evolución de Sanciones (Total, Amarillas y Rojas)',
    width=700,
    height=400
).interactive()

display(chart_detallado)

# Descargar archivo como HTML
from google.colab import files
chart_detallado.save('chart_detallado.html')
files.download('chart_detallado.html')

#Descargar grafico como JPG
chart_detallado.save('chart_detallado.png')
files.download('chart_detallado.png')

alt.Chart(...)

In [63]:
# Definir los periodos de 5 años
def categorizar_periodo(anio):
    if anio < 2005: return '2000-2004'
    elif anio < 2010: return '2005-2009'
    elif anio < 2015: return '2010-2014'
    elif anio < 2020: return '2015-2019'
    else: return '2020+'

# Aplicar la categorización
data_grafico['Periodo'] = data_grafico['Año'].apply(categorizar_periodo)

# Agrupar por Periodo y Tipo
tendencia_periodos = data_grafico.groupby(['Periodo', 'Tipo'])['Cantidad'].sum().reset_index()

# Graficar
chart_periodos = alt.Chart(tendencia_periodos).mark_bar().encode(
    x=alt.X('Periodo:N', title='Periodo de 5 Años'),
    y=alt.Y('Cantidad:Q', title='Total de Sanciones'),
    color=alt.Color('Tipo:N',
                    scale=alt.Scale(domain=['Total', 'Amarilla', 'Roja'],
                                   range=['#333333', '#D4AF37', '#CC0000'])),
    xOffset='Tipo:N',
    tooltip=['Periodo', 'Tipo', 'Cantidad']
).properties(
    title='Faltas por Periodos',
    width=600,
    height=400
).interactive()

display(chart_periodos)

#Descargar archivo HTML
from google.colab import files
chart_periodos.save('chart_periodos.html')
files.download('chart_periodos.html')

#Descargar grafico PNG
chart_periodos.save('chart_periodos.png')
files.download('chart_periodos.png')

alt.Chart(...)

In [64]:
import altair as alt

# Gráfico de barras para la cantidad de partidos por año
chart_partidos_barras = alt.Chart(partidos_por_anio).mark_bar(color='#008080').encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Cantidad de Partidos:Q', title='Número de Partidos', axis=alt.Axis(tickMinStep=1)),
    tooltip=['Año', 'Cantidad de Partidos']
).properties(
    title='Cantidad de Superclásicos Disputados por Año (Vista de Barras)',
    width=700,
    height=300
).interactive()

display(chart_partidos_barras)

#Descargar archivo HTML
from google.colab import files
chart_partidos_barras.save('chart_partidos_barras.html')
files.download('chart_partidos_barras.html')

#Descargar gráfico PNG
chart_partidos_barras.save('chart_partidos_barras.png')
files.download('chart_partidos_barras.png')

alt.Chart(...)

In [65]:
import pandas as pd
import altair as alt

# Identificar columnas de equipo y de falta
columnas_equipo = [col for col in df.columns if 'equipo-jugador' in col]
columnas_falta = [col for col in df.columns if 'tipo-falta' in col]

# Lista para guardar los equipos de cada falta registrada
equipos_con_faltas = []

for i in range(1, 22):
    col_falta = f'tipo-falta-{i}'
    col_equipo = f'equipo-jugador_{i}'
    if col_falta in df.columns and col_equipo in df.columns:
        mask = df[col_falta].notna()
        equipos_con_faltas.extend(df.loc[mask, col_equipo].dropna().tolist())

# Contar faltas por equipo
faltas_equipo_df = pd.Series(equipos_con_faltas).value_counts().reset_index()
faltas_equipo_df.columns = ['Equipo', 'Total Faltas']

# Calcular porcentajes para el tooltip
total_global = faltas_equipo_df['Total Faltas'].sum()
faltas_equipo_df['Porcentaje'] = (faltas_equipo_df['Total Faltas'] / total_global * 100).round(1).astype(str) + '%'

# Definir colores
colores_equipos = {
    'CSD Colo-Colo': '#000000',
    'Universidad de Chile': '#0000FF'
}

# Crear la base del grafico
base = alt.Chart(faltas_equipo_df).encode(
    theta=alt.Theta(field='Total Faltas', type='quantitative', stack=True),
    color=alt.Color(
        field='Equipo',
        type='nominal',
        scale=alt.Scale(
            domain=list(colores_equipos.keys()),
            range=list(colores_equipos.values())
        )
    ),
    tooltip=['Equipo', 'Total Faltas', 'Porcentaje']
)

# Capa de la torta
pie = base.mark_arc(innerRadius=50, outerRadius=150)

# Capa de texto (numeros en blanco centrados en su zona)
text = base.mark_text(radius=100, color='white', size=16, fontWeight='bold').encode(
    text=alt.Text(field='Total Faltas', type='quantitative')
)

# Combinar capas
chart_final = (pie + text).properties(
    title='Amonestaciones por Equipo',
    width=400,
    height=400
)

display(chart_final)

# Descargar archivo HTML
from google.colab import files
chart_final.save('chart_final.html')
files.download('chart_final.html')

#Descargar grafico PNG
chart_final.save('chart_final.png')
files.download('chart_final.png')

alt.LayerChart(...)